; import symbols:

.import snd_init
.import snd_play
.import snd_stop
.import snd_speed
.import snd_songptr
.import snd_instr1
.import snd_instr2
.import snd_instr3

; define names for frequencies

C0      = 0
CS0     = 2
D0      = 4
DS0     = 6
E0      = 8
F0      = 10
FS0     = 12
G0      = 14
GS0     = 16
A0      = 18
AS0     = 20
B0      = 22
C1      = 24
CS1     = 26
D1      = 28
DS1     = 30
E1      = 32
F1      = 34
FS1     = 36
G1      = 38
GS1     = 40
A1      = 42
AS1     = 44
B1      = 46
C2      = 48
CS2     = 50
D2      = 52
DS2     = 54
E2      = 56
F2      = 58
FS2     = 60
G2      = 62
GS2     = 64
A2      = 66
AS2     = 68
B2      = 70
C3      = 72
CS3     = 74
D3      = 76
DS3     = 78
E3      = 80
F3      = 82
FS3     = 84
G3      = 86
GS3     = 88
A3      = 90
AS3     = 92
B3      = 94
C4      = 96
CS4     = 98
D4      = 100
DS4     = 102
E4      = 104
F4      = 106
FS4     = 108
G4      = 110
GS4     = 112
A4      = 114
AS4     = 116
B4      = 118
C5      = 120
CS5     = 122
D5      = 124
DS5     = 126
E5      = 128
F5      = 130
FS5     = 132
G5      = 134
GS5     = 136
A5      = 138
AS5     = 140
B5      = 142

; vim: ft=asm:et:si:ts=8:sts=8:sw=8
